language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: YVwhFvNI2vUBwG/NY7XmPnfxOViUkoy8h4V1fVtlNqv/A07XOxhb1sY0RhzKezIdf91+nDLzxT5+5MswgiLA+yrixD0T5qLazhJGRMBhIl78zCng5iLYuxaDQZo8xpQ/rzl9ODO2iesLNBdZINN5yV4K/3iKcXuZiKIoGBXvPqClyIwaAD/ZhSY5VWmZ+6gYM+N3wm/OAEGgL9DOR9ZBJp58+YWX/RG/4eZNN+xaNM7ZHbkshZcCGV+KWQSboUWegIeCDdkgFpUlYZG0j5flzfPSQTNoOpFaRXI9uVdVVAvPIllGN3S0blC96aZpmRXZUT2Ss2JcSg6ss2VU/Jcx0UFY3I4N7MTqaa3c8RQjGOGNdY5uoXsr2eMd6TJixy73Eya/c4x/5yoWlMBWi9eVzMImbmC35/Uij2dTlhqVcdZS47F+spq1p34guZzXc6vlrgt3y+FlZbi6pI/ZtKApgojr0s0usdQGzkq0lZ+6AydYSs3pshQ3w6XAv/A8iLNVhFxFsbuXWyPyOET5kcxPb/l/d8w85/d4n9ZBaHP/HqGHbwWuw1xBYRiQCiaZ+5D1Zd2dvGCKOgCCoNuO0AyCgV84s7rTiL1a2nmDf4InajjefMK/LrfLeWJsy5S9zR0Xuky5P52JGUUqtX92/mO7FVItYWF7Hdr/f7nV8LkjxnM=
  on:
    tags: true
    repo: cguardia/questions
    python: 3.8
