language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: Yj5JAbOs3Biw9wCje0uj8LQ5f+BK5xRQ8PgIKUet7rd1VMp8lk5t9a6HBxk4I8xVr1XvYp3KhKeGQOrME3q0uw/2srcdzIedNngWglmkHvYBE8arPM980jkY5bZABJtyB/hQIdfPjt7HPRHcCFmZ6saNMNI2YaKlEp4V5oJj9WG9XLUUFd+/s9Z0aJX1j1QSweMK9JTiT8n1DnUrb45YN3p6d9eQfbKCsdawz4zk7T35b+n8hOS9iaJ1+D9vqqoj/et2Uc4XHhgksd5pT8K/h9IRQMYLRKgUnsf5msLe3TTzEnzBBMcquFOC/ZF82FQBI+qVu8kmDSkabyNiwHE2qG98/y1kdBZ6YAHDTQXIyN+KvThpeeelNgA4CGFU70XTaqaD/HRS1ChD2h/OYAVjRRW4DpqeH5kO83KhEqU29NIEdAUtpqigle4Ba7Thb13SGd/eAvdv7/K/885GqdQPdGkzIGTBmq/sPi34Vl8FqtMRgUisFjyWTqPulG0QpfD0SkImwCJIook6FHbrl9irVVXugYdl4h2oXu4fmxCU8lK1lDcq9IZz/EJMzQg4zt1BSzfvsU7WrbSAza++sW4ND4nCUgz41odIbKlRpLzf6+FT97Eqvk7SSTxjXzIefKi3K/gBJFoXY2WUfqbWKVpY2YaFF5uTG924J2/+UIXc3B8=
  on:
    tags: true
    repo: cguardia/questions
    python: 3.8
